### ISSUE TITLE
Error with CKEditor version 4.6.2

### ISSUE THREAD

**Issue by TheInnovativeTechnologist** [w8tcha/CKEditor-CodeMirror-Plugin#111]
It seems your plugin is broken with the latest version of CKEditor.  Works fine with 4.6.1 but not 4.6.2.  Here is the error:

Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('cke_source cke_reset cke_enable_context_menu') contains HTML space characters, which are not valid in tokens.
    at CKEDITOR.dom.element.CKEDITOR.tools.extend.addClass.c [as addClass] (http://cdn.ckeditor.com/4.6.2/full/ckeditor.js:93:184)
    at loadCodeMirror (http://localhost:50090/ckeditor/plugins/codemirror/plugin.js?t=H0CG:624:26)

**Comment by w8tcha** [comment]
At least for me works fine, are you using the latest version of the plugin?

**Comment by TheInnovativeTechnologist** [comment]
Yes I was unless you have changed it since I posted it.

**Comment by aitala** [comment]
I have been having the issues on several sites with the plug in not working -  using the Custom Builder to download CKEditor from their site.

My error is > 

`TypeError: undefined is not an object (evaluating 'window["codemirror_"+b.id].config')`

in line 15081 of ckeditor.js

E

**Comment by w8tcha** [comment]
At least with the latest version of the editor 4.7.0 & plugin 1.16 i no can reproduce the issue

**Comment by aitala** [comment]
I am getting this error with CKEditor 4.9.2 and  the latest version of the plugin.
I am in Safari on MacOS...

**Comment by tallytarik** [comment]
@aitala Not sure if you ended up solving your problem, but I encountered the same and then figured out what the issue was!

I had downloaded the version from the [plugin's page on ckeditor.com](https://ckeditor.com/cke4/addon/codemirror), but this is **not** the latest version.

The latest version is on the [releases](https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/releases) page here on GitHub, and works with CKEditor 4.9.2.
