### ISSUE TITLE
Issue with rendering source mode

### ISSUE THREAD

**Issue by dsuckau** [w8tcha/CKEditor-CodeMirror-Plugin#94]
Hello,

sometimes, when using CodeMirror-Plugin, if I switch to source mode, it does not render correctly. The left bar, which includes the line numbers of the source code, sometimes has a wrong width and position. Furthermore the underlying code is not completely visible.

If you toggle again the mode, it is looks good again most of the times.
I am using latest Firefox on Windows 7.

Here it is correct:

![1](https://cloud.githubusercontent.com/assets/1607492/10041664/fe65f446-61e5-11e5-8be5-41912f1c3a72.png)

Wrong width and no line numbers:

![2](https://cloud.githubusercontent.com/assets/1607492/10041665/024a831a-61e6-11e5-86e8-c63e836184fb.png)

Wrong position, width and no line numbers:

![3](https://cloud.githubusercontent.com/assets/1607492/10041666/057d88e8-61e6-11e5-9a22-9917abbc520e.png)

Any ideas?

**Comment by dsuckau** [comment]
Oh sorry: I am using the latest Firefox version on Windows 7.

**Comment by jamespatterson** [comment]
I just encountered this issue. I resolved it by making sure the editor is visible during the CodeMirror initialization. It appears CodeMirror sets many inline styles via JS calculations, which will be wrong if the DOM is not displaying the node(s).

In my case, I have many CKEditors on screen at once, with only the first one visible initially. The first one looked fine, but the others were broken just like you describe. I fixed it with some `visibility:hidden` usage, instead of `display:none` and then revealing the first editor via CKEditor's `instanceReady` event.

Since CodeMirror is performing the calculations, not this CKEditor plugin, my guess is the issue won't be resolved here. Make sure your parent elements are all visible at the time of initialization, and report back if it is resolved for you.
